exports.base = function () {
	var base = [
	"Achou que não ia ter mais Choque de Cultura? Achou errado, otário!",
	"Sou obrigado a concordar com o Palestrinha.",
	"Ambiente de música é ambiente de droga!",
	"Só magia top, rogerinho. Num tem um haduken, num tem nada xoxo no filme não, só magia top!",
	"Filme do Harry Potter sem o Harry Potter é igual filme dos 10 mandamentos sem Jesus",
	"O que é cultura jovem? Urso, piercing.",
	"O jovem já não vai mais numa boate. O jovem já não marca mais um racha, não rouba um disco numa loja, não sai na porrada na rua com a criança. Hoje só quer ficar em casa assistindo sériezinha de terror.",
	"Uma série é um filme gigante divido em vários capítulos.",
	"A série é um Goonies com uma pitadinha de Scooby-doo.",
	"Criança podia fumar dentro da escola. Que é um negócio que eu particularmente sinto falta.",
	"Nos anos 80 teve uma epidemia de cocaína. Todo mundo acordava tarde.",
	"Eu achei essa música aí meio alta no trailler.",
	"Lá nos Estados Unidos eles dão armas no natal para as crianças. Eles levam o natal mais a sério.",
	"Podia ser o Stranger mais Things ainda.",
	"Um Stranger Things muito louco.",
	"Um Stranger Things do barulho.",
	"Um Stranger Things de verão.",
	"Um Stranger Things perdido na Tailândia.",
	"Um Stranger Things o retorno.",
	"Um Stranger Things sai de férias.",
	"Princesa Xuxa e o Stranger Things.",
	"É um erro você dar um problema sobrenatural para adolescente.",
	"É triste isso, eim.",
	"Nada a vê.",
	"Você achou que eu ia te chamar de otário hoje? Achou errado, otário.",
	"A internet é o local onde mais tem jovem confuso.",
	"O problema do Maurílio é que ele tem muita informação pra uma cabeça pequena.",
	"A Marvel é uma violência mais moleque... é como se fosse uma coça de mãe. Já a DC é mais agressiva... é como se fosse um espancamento de pai alcoólatra.",
	"O Estados Unidos é patriota. O Brasil é bagunça.",
	"O brasileiro gosta de falar mal do brasileiro.",
	"Já tive a oportunidade de me envolver num acidente com Thor Batista.",
	"A sorte é que eu conhecia bem o veículo e me alimentei da espuma do banco da Towner. Que é carboidrato puro.",
	"Você é nosso herói, Renan!",
	"Gente humilde apanha.",
	"O Papa hoje é uma franquia. É igual o Bozo que tem vários Bozo.",
	"Bobo.",
	"Vou resumir em uma palavra só: bobo.",
	"O bronzeamente muda a feição também? Muda. Olha o Marcos Mion.",
	"Homem de ferro é o Eike Batista com dinheiro.",
	"O cidadão comum ele não tem o conhecimento.",
	"Uma aranha caranguejeira lindíssima... do tamanho de um piréx... toda peluda.",
	"Eu joguei ele pra cima pra ver se ele tinha super poderes",
	"Tá pegando fogo hoje, Rogerinho.",
	"A gente não pode resumir como DC sendo um universo de playboy e Marvel sendo um universo de baderneiros.",
	"Definiu muito bem. Ou é playboy ou é baderneiro.",
	"DC. Marvel. D. Marvel.",
	"Ele quer ser diferente, Rogerinho.",
	"Jesus é da Marvel? Jesus é da Disney, rapá.",
	"Tá certa a indignação.",
	"Sua vida é uma bosta.",
	"Eu já sabia do histórico de drogas desse Bozo.",
	"Não tem a Vovó Mafalda. Que é um erro histórico.",
	"Pela liberdade. Pela família. Pelo planeta. Achei que isso era voto de impeachment. Achei até que era cartaz da lava jato.",
	"Naaaa na na na na na... e tá faltando emprego no planeta dos... Cala a boca. Cala a boca.",
	"Se você quiser pensar você vai jogar um RPG.",
	"Essa mania de querer botar computador em tudo.",
	"Não tem que dar inteligência pra carro.",
	"Eu sou contra inteligência.",
	"Brasil é um país de imposto.",
	"Dei uma cochilada no início.",
	"Isso é uma porta dos desesperados, mas os macacos ficam de fora.",
	"Os primitivos que inventaram a covardia aí, ó.",
	"O certo é brigar na mão livre.",
	"Não pode ver uma pedra que quer tocar.",
	"Está cheio de ponto bom ali pra meter um Jequiti. Fazer um dinheiro forte.",
	"Com o troco dava pra fazer um Debi e Loide.",
	"As vezes eu sonho que estou dirigindo e quando acordo estou dirigindo mesmo.",
	"Aquela reta é uma delícia pra tirar um cochilo.",
	"Naaaaaave lenta pra caralho.",
	"Guerra nas estrelas sem guerra.",
	"Posso pedir uma salva de palmas para o Stanley?",
	"O futuro é a internet.",
	"Hospital é um perigo. As vezes você atropela uma pessoa ela tá bem. Ela vai pro hospital e ela morre.",
	"Aqui não é programa de música. É programa de cultura.",
	"Cês cai fora de ambiente de música.",
	"Isso é muito som, irmão.",
	"Preconceito é coisa de cigano." ,
	"Os amantes do 24 quadros por segundo, cinéfilos...",
	"Uma vez eu fui limpar a caixa d'água da casa da minha mãe e encontrei 6 pombos mortos lá.",
	"Peixe odeia jazz.",
	"Ele tá seduzindo ela pra fugir.",
	"O jacaré não tem chance no Brasil.",
	"Acho que o anabolizante tá derretendo sua cabeça.",
	"Jacaré é traiçoeiro.",
	"O jacaré não faz o que combina.",
	"E Veneza por algum acaso fica aonde? Fica embaixo d'água.",
	"Não comprem. Adotem.",
	"Que cadelinha linda. Uma lição de vida.",
	"O filme é bom. A história é que atrapalha.",
	"Aqui é profissional",
	"Mulheril? Temos. Explosão e porradaria? Temos.",
	"Quando você pula muito alto você voa.",
	"Você não é refém da gravidade. Você é refém dos seus sonhos.",
	"Achou errado, otário!",
	"Ambiente de música é ambiente de droga!",
	"Sou contra alegria em ambiente de trabalho.",
	"O Fausto é vingativo.",
	"Roda aí, Simone.",
	"Mecânico é safado, rapá.",
	"Golfinho é mau-caráter.",
	"Aqui não é pôr do sol pra idiota ficar batendo palma.",
	"Isso aí é droga.",
	"Sua vida é uma bosta.",
	"Simone, solta o trailer aí.",
	"Tem que acabar com a justiça!",
	"Eu transei uma vez.",
	"Eu vou pro cinema pra me divertir. Se fosse pra ficar deprimido eu ia trabalhar ou ficar com a minha família.",
	"Se equivovou amante da sétima arte!",
	"Olá amantes da sétima arte.",
	"A justiça é muito injusta.",
	"Boa noite amantes da sétima arte.",
	"Qualquer carro dá pra capotar, rapá.",
	"Que porra é essa de força, irmão?",
	"Não tinha um adulto consciente pra botar uma arma de fogo na mão dessa criança?",
	"Eu nunca matei ninguém propositalmente.",
	"Soco é isso aqui, ó.",
	"Eu sou uma pessoa normal. Fiz catequese pra pegar mulher.",
	"Quem é Selton Mello?",
	"Computador... computador... é tudo computador essa porra!",
	"Tu tem que ligar pro Maicon despachante que o cara desenrola pra você furar fila de idoso.",
	"Falo isso com tranquilidade.",
	"É a mentira que mantém o casal junto.",
	"Você é assim, é tudo pra mim, você é meu guerreirinho.",
	"O Caldeirão do Huck, sou grande fã desse programa... porque ele humilha o pobre... humilha, humilha, humilha e depois ajuda.",
	"Ele nasceu pra ser idoso.",
	"Só magia top!",
	"No cruzamento a preferência é de quem tem coragem.",
	"Eu já atropelei um Beto. Ficamos amigos.",
	"Ninguém transa. As pessoas falam que transam, mas não transam. Dá muito trabalho.",
	"Tem Uber que tem Choquito dentro do carro. Inescrupulosos.",
	"É energia aqui, ó.",
	"Qual a única coisa que tem que ter no filme do Rambo? Rambo.",
	"Cadê Renanzinho?",
	"Vou resumir em uma palavra: show!",
	"Quando pego um táxi eu sento no motorista e o taxista vai atrás. Eu vou conduzindo o veículo.",
	"Muitas vezes quem atropela é tido como culpado.",
	"Ele é meu guerreirinho.",
	"Quando você chega com um pedaço de pau numa briga, a outra pessoa quer logo conversar.",
	"Você sabe que no cruzamento a preferência é de quem tá mais rápido.",
	"Eu vejo o filme para não ter que ler o livro.",
	"Ele tem talento pra isso.",
	"Só senti falta de um sonzinho do Jota Quest.",
	"Música boa pra peixe é um Natirutizinho... música de praia.",
	"Uma vez meu filho pegou fogo.",
	"Meu filho é minha família duas vezes. É meu filho e meu primo de segundo grau.",
	"Fings! É Fings a palavra.",
	"Forrest Gump é a história de um homem que é burro.",
	"Jesus daqui a pouco vai vim nos Vingadores. Porque ele é justiceiro.",
	"Quando um filme tem poesia, tem trem.",
	"Eu não imaginava a intensidade desse problema. O abismo da droga.",
	"Ele tem talento pra isso!"
	];

	return base;
};